### ISSUE TITLE
RangeError: Unsupported time zone specified undefined

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2498]
## The Issue
This pops up once in a while - not sure which timezone or bug is causing it. 
```
 RangeError: Unsupported time zone specified undefined
   at new DateTimeFormat (native)
   at Date.toLocaleDateString (native)
   at p.render (file:///opt/LBRY/resources/app.asar/ui.js:12:100049)
   at Po (file:///opt/LBRY/resources/app.asar/ui.js:269:63001)
   at To (file:///opt/LBRY/resources/app.asar/ui.js:269:62796)
   at Io (file:///opt/LBRY/resources/app.asar/ui.js:269:66630)
   at qi (file:///opt/LBRY/resources/app.asar/ui.js:269:90674)
   at $i (file:///opt/LBRY/resources/app.asar/ui.js:269:91058)
   at Pl (file:///opt/LBRY/resources/app.asar/ui.js:269:97945)
   at Sl (file:///opt/LBRY/resources/app.asar/ui.js:269:97325)
```
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Think this is related to the local in https://github.com/lbryio/lbry-desktop/blob/be89a119046c31d238056a935848adfc7c440398/src/ui/index.jsx#L195

A user in South Africa ran into this and it was fixed by changing their locale. Maybe try/catch and then default to US if it fails?

**Comment by tzarebczan** [comment]
Here's a recent similar one: ```User(xxxxx) Desktop Error: Uncaught error
app version: 0.35.3
sdk version: 0.40.0
page: #/@MaxWrist:0/maxwrist-hits-one-million:5
RangeError: Invalid language tag: de_DE
   at new DateTimeFormat (native)
   at Date.toLocaleDateString (native)
   at p.render (file:///opt/LBRY/resources/app.asar/ui.js:22:15089)
   at Oa (file:///opt/LBRY/resources/app.asar/ui.js:240:63001)
   at ja (file:///opt/LBRY/resources/app.asar/ui.js:240:62796)
   at La (file:///opt/LBRY/resources/app.asar/ui.js:240:66630)
   at Yo (file:///opt/LBRY/resources/app.asar/ui.js:240:90674)
   at $o (file:///opt/LBRY/resources/app.asar/ui.js:240:91058)
   at As (file:///opt/LBRY/resources/app.asar/ui.js:240:97945)
   at js (file:///opt/LBRY/resources/app.asar/ui.js:240:97325)```

**Comment by AdityaSrivast** [comment]
@tzarebczan I would like to work on this issue. Can you guide me on what's to be done, please?

**Comment by seanyesmunt** [comment]
Sorry @AdityaSrivast 

I'm pretty sure this has been fixed. The issue was just never closed.

**Comment by tzarebczan** [comment]
This is still an issue in some cases. Reaching out to the user to see what localization settings they are using: 

```
app version: 0.36.1
sdk version: 0.42.1
page: #/@TheLinuxGamer:f/i-got-my-hands-on-the-librem5-phone:2
RangeError: Unsupported time zone specified undefined
   at new DateTimeFormat (native)
   at Date.toLocaleDateString (native)
   at d.render (file:///app/lbry-app/resources/app.asar/ui.js:22:14876)
   at Oi (file:///app/lbry-app/resources/app.asar/ui.js:226:63001)
   at ji (file:///app/lbry-app/resources/app.asar/ui.js:226:62796)
   at Ni (file:///app/lbry-app/resources/app.asar/ui.js:226:66630)
   at qo (file:///app/lbry-app/resources/app.asar/ui.js:226:90674)
   at $o (file:///app/lbry-app/resources/app.asar/ui.js:226:91058)
   at As (file:///app/lbry-app/resources/app.asar/ui.js:226:97945)
   at js (file:///app/lbry-app/resources/app.asar/ui.js:226:97325)
```

**Comment by seanyesmunt** [comment]
Will be included in the next app release

**Comment by tzarebczan** [comment]
Still happens on the wallet page: 
```
User(2205995) Desktop Error: Uncaught error
app version: 0.38.2
sdk version: 0.50.1
page: #/$/wallet
RangeError: Unsupported time zone specified undefined```

**Comment by tzarebczan** [comment]
Also on settings page: 
```
User(2590497) Desktop Error: Uncaught error
app version: 0.39.1
sdk version: 0.54.1
page: #/$/settings
RangeError: Unsupported time zone specified undefined
   at new DateTimeFormat (native)
   at Date.toLocaleTimeString (native)
   at n.r.to12Hour (file:///app/lbry-app/resources/app.asar/ui.js:211:60724)
   at file:///app/lbry-app/resources/app.asar/ui.js:211:67365
   at Array.map (<anonymous>)
   at n.r.render (file:///app/lbry-app/resources/app.asar/ui.js:211:67299)
   at ja (file:///app/lbry-app/resources/app.asar/ui.js:286:63002)
   at Oa (file:///app/lbry-app/resources/app.asar/ui.js:286:62797)
   at Ia (file:///app/lbry-app/resources/app.asar/ui.js:286:66631)
   at qo (file:///app/lbry-app/resources/app.asar/ui.js:286:90675)
   at Yo (file:///app/lbry-app/resources/app.asar/ui.js:286:91059)
   at As (file:///app/lbry-app/resources/app.asar/ui.js:286:97946)
   at Os (file:///app/lbry-app/resources/app.asar/ui.js:286:97326)
   at Le (file:///app/lbry-app/resources/app.asar/ui.js:286:103717)
   at Ne (file:///app/lbry-app/resources/app.asar/ui.js:286:10304)
   at On (file:///app/lbry-app/resources/app.asar/ui.js:286:30826)
```

**Comment by HarshKhandeparkar** [comment]
Hi! Is is open for grabs? I am new here and I want to contribute. I may need some guidance initially as I am not familiar with the codebase.

**Comment by tzarebczan** [comment]
@HarshKhandeparkar thanks for taking a shot. This one may be tougher to reproduce since we aren't sure of the exact scenario yet, but it was fixed previously in other components. 

Welcome to LBRY and check out lbry.tech/contribute to get an overview

**Comment by HarshKhandeparkar** [comment]
I looked through the good first issues but couldn't find one that is not
taken up or already fixed. Can you suggest something for me to do? Like
search a specific keyword or label?

**Comment by HarshKhandeparkar** [comment]
I want to try something super simple or even stupid like a typo fix just
get used to the codebase and the development. After that, I can contribute
to other issues.

**Comment by tzarebczan** [comment]
I've tagged a few more issues as help wanted and good first issue, check some of those out. Or maybe find something else you come across while familiarizing yourself with the app.

**Comment by HarshKhandeparkar** [comment]
Oh thank you! I'll have a look tomorrow.

**Comment by tzarebczan** [comment]
Have not seen this happen.
