### ISSUE TITLE
Users are not captured properly on lbry.tv

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#2544]
I have been going to  beta.lbry.tv and lbry.tv multiple times a week for a number of weeks now. Almost every time I visit, it thinks that I am a new user. 

This has the side effect of misinforming our analytics of the number of users to the site. It is also incorrectly flooding internal-apis with users that are not real users. I flagged it a few weeks back but I see its not fixed yet so I wanted to create an issue so we don't overlook it. 

I would expect we can easily leverage cookies,local storage and ip addresses to get this more accurate.

**Comment by seanyesmunt** [comment]
Fixed with #2545

**Comment by tiger5226** [comment]
awesome team! @kauffj @robvsmith This should correct our community pulse numbers which are grossly wrong.

**Comment by tiger5226** [comment]
I just tested this out on beta.lbry.tv and its still not fixed. I went to the site clicked im in yesterday. Watched a few videos etc. Then today I went back to the site and it treated me as a new user again. Just to be clear, I am not "logging in" I am an anonymous user, but we should not be creating new users every time they access the site. This would not be scalable.

**Comment by sayplastic** [comment]
@tiger5226 this is clearly not working for you the way it should, no discussion about it. Is the problem there when you just close your browser and reopen it?

**Comment by tiger5226** [comment]
I am going to close this because what I was using to determine if it was worked is not accurate. The yrbl asking if you are in does not mean you are a new user. Looking at other details it appears to be work on the latest update. I see everything in the past 24 hours. So this looks to have fixed that issue. 

However, there is another issue somewhere. We are seeing a large number users and they are all one time users, never returning. Maybe there is a cookie setting issue for it for most users. Not sure exactly what it is yet. So I will close this issue and create a new one once I figure it out.
