### ISSUE TITLE
Searches with forward slashes returns no results

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#2731]
When searching **GNU/Linux**, or **cats/dogs**, or any search that contains a forward slash, it returns no results.

**Comment by kauffj** [comment]
I'm guessing `/` isn't the only character that causes this issue. When working on this, it should be solved for (ideally) all possible inputs.

**Comment by tzarebczan** [comment]
Still an issue. The search results return, but nothing shows in app. Maybe a bad claim?
