### ISSUE TITLE
iOS 14 Safari: Video freezes, audio keeps going (lbry.tv)

### ISSUE THREAD

**Issue by anohren** [lbryio/lbry-desktop#5251]
When watching a video, after some random time watching (in full screen) the picture freezes on a frame while the audio keeps going. This happens in multiple videos from different authors. 

Unfortunately I don't have much info about which type of videos exhibit this behavior since I can't seem to find much metadata about them other than size and file type (not even their resolution). 

I don't recall having this problem on any other video sites than lbry. 

This happens on an iPhone 8 with iOS 14.2 in Safari.

**Comment by seanyesmunt** [comment]
@anohren Does it happen every time? Can you share a link to a video that bugs out?

**Comment by anohren** [comment]
Probably not every time since it doesn't freeze at the same spots from what I can tell. 

Sure. Here's one that froze after quite some time of watching: 

https://lbry.tv/@rossmanngroup:a/on-the-job-learning-works-when-there-s-a:9

**Comment by AlphaXyXy** [comment]
:(

**Comment by DispatchCommit** [comment]
Another potentially caused by #5323 as well. Potentially fixed by #5344 

I'm not certain it is, but it's possible that overriding Safari's native HLS player has a negative performance hit to longer videos that are transcoded and delivered over HLS (.m3u8 streams) and running into issues. My suspicion is that this does not occur on shorter videos because they are either mp4's (and therefore not affected by HLS-related issues) and/or shorter HLS streams do not have enough duration to cause a noticeable degradation, while longer streams do encounter this issue.

**Comment by anohren** [comment]
@DispatchCommit 
Is it possible for me to see somewhere when that change goes live?



Still an issue in iOS 14.4: went to Picture in Picture, switched away from safari, minimized the PiP window to the side, and when I restored it the picture was stuck.

**Comment by tzarebczan** [comment]
Please let us know if it's still happening by re-opening the issue. We've pushed various fixes into the video players.
