### ISSUE TITLE
Open button, opens folder if file has been deleted on v16

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-desktop#586]
## The Issue

If you download some content on v16 and then delete the file outside of the app. It does not tell you the file is missing and redownloads. It opens the download folder instead

### Steps to reproduce
1. Download any content
2.Go to the file explorer and delete that file from your downloads folder
3. click on the content you previously downloaded from the main page and then click open

### Expected behaviour
Should ask you to download again or tell you it has been deleted from the system

### Actual behaviour
Opens the downloads folder instead

## System Configuration

 

  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "###########",
    "lbrynet_version": "0.16.0",
    "lbryschema_version": "0.0.11",
    "lbryum_version": "3.1.7",
    "os_release": "4.4.0-93-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }

**Comment by tzarebczan** [comment]
@oakey22 can you try this on the latest RC/master? It should be fixed but will wait for your confirmation.

**Comment by oakey22** [comment]
This is still happening in the new v16 RC7. If the file is not in your downloads directory it opens the directory when you click Open

**Comment by oakey22** [comment]
https://spee.ch/71c8c83934d31de9adb43233b57c765159759c70/jsdkljsdkljlksa.gif

**Comment by tzarebczan** [comment]
I'm pretty sure this was always the functionality.  If you try to stream the content again, that's when it tries to redownload it. Clicking Open causes the file to be opened in the local file explorer.  

I agree it should check if the file exists and confirms if the user wants to re-download/regenerate it.

**Comment by tzarebczan** [comment]
We should check that the file exists before opening it, and if not, allow the user to re-download it.

**Comment by kauffj** [comment]
A bit torn on this one. Should the daemon be doing more to verify files exist or is this always the job of the application layer? 

At first thought, I'm inclined to say if the daemon is returning a path, it is implicitly promising the file is actually there.

@eukreign @skhameneh maybe you could discuss and reach consensus on where this responsibility should reside?

**Comment by alyssaoc** [comment]
@jackrobison is this hard/worth adding to the daemon?

**Comment by tzarebczan** [comment]
This will no longer show as an option if the file exists. In the file info area, there's a note if the file was deleted
