### ISSUE TITLE
pre roll ads fall out

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6477]
- [ ] app crash in incognito embeds
- [ ] some ads can be clicked, open in new tab, and ad pauses - there's no way to resume or skip
- [ ] do not load any ad stuff when signed in (https://tag.targeting.unrulymedia.com/rmp/216276/0/vast2?vastfw=vpaid&w=300&h=500&url=https://odysee.com/@Kona_and_Suba_Guinea_Pig_Adventures:c/this-is-peanut-the-guinea-pig:1 is called) 
- [ ] cut off at the bottom a bit and have a top black bar (https://lbryians.slack.com/archives/C81FGKR51/p1625678103453600?thread_ts=1625646978.442100&cid=C81FGKR51)

**Comment by infinite-persistence** [comment]
Regression:
- [ ] The issue of videos not switching correctly (previously fixed by restoring the double `src` call) is back again.
- [ ] The "Retry" button is gone, so we are back to having to do a full reload or re-enter the page.  A retry almost always loads for me. Either fix to prevent this scenario, auto-retry, and put back the button?
- [ ] Minor:  It doesn't make sense to keep spinning when it already failed (makes user think whether to wait or not). This was previously fixed.
    - <img src="https://user-images.githubusercontent.com/64950861/126037059-9ab18149-4b26-47c0-893d-fb0901a938a2.png" width="480">

**Comment by tzarebczan** [comment]
We are getting more reports of adblockers blocking various calls/media on the page after we pushed this change, even when logged in. It may be related to the ad calls still getting made when logged in, but not sure. Reached out to adblocker.

**Comment by tzarebczan** [comment]
Confirmed that my findings are causing issues for signed in users with pop up blockers due to the call still being made while signed in. This prevents the video from playing (probably just from this error, and potentially not from our domain being blacklisted) 
![image](https://user-images.githubusercontent.com/8120721/126342744-95bb2e95-f802-4732-a838-4394e3e39641.png)

**Comment by tzarebczan** [comment]
Some others 
- [ ] don't load for signed in users: https://imasdk.googleapis.com/js/sdkloader/ima3.js
- [ ] double head request causes double master playlist call: 
![image](https://user-images.githubusercontent.com/8120721/126347574-a180d0b4-5494-4b98-9366-6d5d0aeb7519.png)

**Comment by kauffj** [comment]
@mayeaux this is an older ads issue, if it's not useful, please close it
