### ISSUE TITLE
large odysee logo over embeds

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6771]
https://odysee.com/$/embed/so-it-might-get-worse.../9c404a0d525514ba698efa8ff0bfd5fbee8435d0

**Comment by infinite-persistence** [comment]
Fixed by #6774

**Comment by Eniamza** [comment]
@tzarebczan The issue still persists for smaller frame ratio because the title and logo won't fade away on the play
![image](https://user-images.githubusercontent.com/65225917/128609558-afb9f4ba-4e72-4085-8e3c-0094fcb55502.png)
![image](https://user-images.githubusercontent.com/65225917/128609572-ad18c135-f02e-4d06-bdbb-7f2f3c486a4a.png)

I think it'd be worth adding an onPlay fade action too!
